from __future__ import annotations

from typing import Any


DEFAULT_SETTINGS: dict[str, Any] = {
    "project": {
        "name": "NeXa",
        "version": "0.7.0",
        "stage": "premium-product-foundation",
    },
    "user": {
        "name": "Andrzej",
    },
    "voice_input": {
        "enabled": True,
        "engine": "faster_whisper",
        "wake_engine": "openwakeword",
        "single_capture_mode": True,
        "wake_model_path": "models/wake/nexa.onnx",
        "wake_threshold": 0.5,
        "wake_trigger_level": 2,
        "wake_block_ms": 80,
        "wake_vad_threshold": 0.28,
        "wake_enable_speex_noise_suppression": True,
        "wake_debug": False,
        "wake_barge_in_enabled": True,
        "wake_barge_in_timeout_seconds": 0.18,
        "wake_barge_in_min_output_age_seconds": 0.35,
        "wake_barge_in_resume_timeout_seconds": 1.25,
        "wake_barge_in_refractory_seconds": 0.75,
        "device_index": None,
        "device_name_contains": None,
        "timeout_seconds": 7,
        "active_listen_window_seconds": 6.0,
        "thinking_ack_seconds": 1.2,
        "wake_ack_prefetch_on_boot": True,
        "active_window_retry_min_remaining_seconds": 0.35,
        "debug": False,
        "sample_rate": 16000,
        "max_record_seconds": 6.5,
        "end_silence_seconds": 0.6,
        "pre_roll_seconds": 0.45,
        "blocksize": 512,
        "min_speech_seconds": 0.2,
        "transcription_timeout_seconds": 10.0,
        "threads": 4,
        "language": "auto",
        "vad_enabled": True,
        "vad_threshold": 0.3,
        "vad_min_speech_ms": 120,
        "vad_min_silence_ms": 250,
        "vad_speech_pad_ms": 180,
        "compute_type": "int8",
        "beam_size": 1,
        "best_of": 1,
        "model_size_or_path": "tiny",
        "whisper_cli_path": "whisper.cpp/build/bin/whisper-cli",
        "model_path": "models/ggml-base.bin",
        "vad_model_path": "models/ggml-silero-v6.2.0.bin",
    },
    "voice_engine": {
        "enabled": False,
        "version": "v2",
        "mode": "legacy",
        "realtime_audio_bus_enabled": False,
        "faster_whisper_audio_bus_tap_enabled": False,
        "faster_whisper_audio_bus_tap_max_duration_seconds": 3.0,
        "vad_shadow_enabled": False,
        "vad_shadow_max_frames_per_observation": 96,
        "vad_shadow_speech_threshold": 0.5,
        "vad_shadow_min_speech_ms": 120,
        "vad_shadow_min_silence_ms": 250,
        "vad_timing_bridge_enabled": False,
        "vad_timing_bridge_log_path": (
            "var/data/voice_engine_v2_vad_timing_bridge.jsonl"
        ),
        "command_asr_shadow_bridge_enabled": False,
        "vosk_live_shadow_contract_enabled": False,
        "vad_endpointing_enabled": False,
        "command_first_enabled": False,
        "fallback_to_legacy_enabled": True,
        "metrics_enabled": True,
        "shadow_mode_enabled": False,
        "shadow_log_path": "var/data/voice_engine_v2_shadow.jsonl",
        "runtime_candidates_enabled": False,
        "runtime_candidate_intent_allowlist": [
            "assistant.identity",
            "system.current_time",
        ],
        "runtime_candidate_log_path": (
            "var/data/voice_engine_v2_runtime_candidates.jsonl"
        ),
        "pre_stt_shadow_enabled": False,
        "pre_stt_shadow_log_path": (
            "var/data/voice_engine_v2_pre_stt_shadow.jsonl"
        ),
        "legacy_removal_stage": "after_voice_engine_v2_runtime_acceptance",
    },
    "voice_output": {
        "enabled": True,
        "engine": "piper",
        "default_language": "en",
        "speed": 155,
        "pitch": 58,
        "voices": {
            "pl": "pl+f3",
            "en": "en+f3",
        },
        "piper_models": {
            "pl": {
                "model": "voices/piper/pl_PL-gosia-medium.onnx",
                "config": "voices/piper/pl_PL-gosia-medium.onnx.json",
            },
            "en": {
                "model": "voices/piper/en_GB-jenny_dioco-medium.onnx",
                "config": "voices/piper/en_GB-jenny_dioco-medium.onnx.json",
            },
        },
        "process_poll_seconds": 0.02,
        "playback_poll_seconds": 0.005,
        "preferred_playback_backend": "aplay",
        "direct_sounddevice_playback_enabled": False,
    },
    "display": {
        "enabled": True,
        "driver": "waveshare_2inch",
        "interface": "spi",
        "port": 1,
        "address": 60,
        "rotate": 0,
        "width": 240,
        "height": 320,
        "gpio_dc": 25,
        "gpio_rst": 27,
        "gpio_light": 18,
        "spi_port": 0,
        "spi_device": 0,
        "default_overlay_seconds": 8,
        "boot_overlay_seconds": 2.4,
        "developer_overlay": {
            "enabled": True,
            "title": "DEV",
            "refresh_on_boot": True,
            "refresh_on_turn_finish": True,
},
    },
    "timers": {
        "default_focus_minutes": 25,
        "default_break_minutes": 5,
    },
    "streaming": {
        "dialogue_stream_mode": "sentence",
        "live_llm_sentence_streaming_enabled": True,
        "inter_chunk_pause_seconds": 0.0,
        "max_display_lines": 2,
        "max_display_chars_per_line": 20,
        "prefetch_action_responses": True,
        "prefetch_text_responses": True,
        "prefetch_text_response_max_chars": 220,
    },
    "audio_coordination": {
        "self_hearing_hold_seconds": 0.32,
        "listen_resume_poll_seconds": 0.04,
    },
    "conversation": {
        "max_turns": 8,
        "max_total_chars": 1800,
    },
   "llm": {
    "enabled": False,
    "runner": "hailo-ollama",
    "command": "llama-cli",
    "model_path": "models/Qwen2.5-1.5B-Instruct-Q4_K_M.gguf",
    "n_predict": 96,
    "temperature": 0.7,
    "top_p": 0.9,
    "top_k": 40,
    "ctx_size": 2048,
    "threads": 4,
    "timeout_seconds": 18.0,
    "repeat_penalty": 1.1,
    "max_prompt_chars": 2400,
    "prefer_json": False,
    "stream_sentence_min_chars": 18,
    "stream_sentence_soft_max_chars": 120,
    "server_url": "http://127.0.0.1:8000",
    "server_chat_path": "/api/chat",
    "server_health_path": "/hailo/v1/list",
    "server_api_key": "",
    "server_model_name": "qwen2:1.5b",
    "server_use_openai_compat": False,
    "server_connect_timeout_seconds": 3.0,
    "require_persistent_backend": True,
    "allow_cli_fallback": False,
    "stream_responses": True,
    "startup_warmup": True,
    "startup_warmup_timeout_seconds": 8.0,
},
    "logging": {
        "enabled": True,
        "console_enabled": False,
        "log_file": "var/logs/system.log",
        "max_bytes": 1_000_000,
        "backup_count": 2,
    },
    "system": {
        "allow_shutdown_commands": False,
        "shutdown_command": ["systemctl", "poweroff"],
    },
    "deployment": {
        "unit_output_dir": "deploy/systemd",
        "app_unit_name": "nexa.service",
        "llm_unit_name": "nexa-llm.service",
        "user": "",
        "group": "",
        "python_path": ".venv/bin/python",
        "environment_file": "config/systemd/nexa.env",
        "app_restart": "on-failure",
        "app_restart_sec": 2.0,
        "app_start_limit_interval_sec": 30,
        "app_start_limit_burst": 5,
        "app_timeout_stop_sec": 25.0,
        "app_kill_signal": "SIGINT",
        "app_environment": {},
        "llm_service_enabled": False,
        "llm_service_command": [],
        "llm_service_working_directory": "",
        "llm_restart": "on-failure",
        "llm_restart_sec": 2.0,
        "llm_start_limit_interval_sec": 30,
        "llm_start_limit_burst": 5,
        "llm_timeout_stop_sec": 20.0,
        "llm_kill_signal": "SIGTERM",
        "llm_environment": {},
    },
    "runtime_product": {
        "persist_status": True,
        "status_path": "var/data/runtime_status.json",
        "required_ready_components": ["voice_input", "voice_output", "display"],
        "auto_recovery_components": ["llm"],
        "treat_llm_as_required_when_enabled": False,
    },
    "fast_command_lane": {
        "enabled": True,
    },
    "visual_shell": {
        "enabled": True,
        "voice_commands_enabled": True,
        "speak_acknowledgements_enabled": True,
        "transport": {
            "host": "127.0.0.1",
            "port": 8765,
            "timeout_sec": 0.10,
        },
        "autostart": {
            "enabled": True,
            "audio_driver": "Dummy",
            "launch_command": [
                "modules/presentation/visual_shell/bin/run_visual_shell.sh"
            ],
        },
    },
    "vision": {
        "enabled": False,
        "backend": "picamera2",
        "fallback_backend": "opencv",
        "camera_index": 0,
        "frame_width": 1280,
        "frame_height": 720,
        "warmup_seconds": 0.35,
        "capture_timeout_seconds": 2.0,
        "lazy_start": True,
        "hflip": False,
        "vflip": False,
        "people_detection_enabled": False,
        "people_detector_backend": "opencv_hog",
        "people_detector_min_confidence": 0.45,
        "people_detector_min_area_ratio": 0.025,
        "people_detector_min_height_ratio": 0.18,
        "people_detector_max_width_ratio": 0.85,
        "people_detector_use_clahe": True,
        "people_detector_upscale_factor": 1.35,
        "people_detector_desk_roi_enabled": True,
        "people_detector_roi_x_min": 0.10,
        "people_detector_roi_y_min": 0.08,
        "people_detector_roi_x_max": 0.90,
        "people_detector_roi_y_max": 0.98,
        "people_detector_hybrid_use_hog_secondary": False,
        "people_detector_hybrid_body_width_multiplier": 2.6,
        "people_detector_hybrid_body_height_multiplier": 5.5,
        "object_detector_hailo_hef_path": "/usr/share/hailo-models/yolov11m_h10.hef",
        "object_detector_hailo_score_threshold": 0.35,
        "object_detector_hailo_max_detections": 30,
        "object_detector_hailo_initial_cadence_hz": 2.0,
        "object_detector_hailo_desk_relevant_only": False,
        "face_detection_enabled": False,
        "face_detector_backend": "opencv_haar",
        "face_detector_min_area_ratio": 0.002,
        "face_detector_use_clahe": True,
        "face_detector_roi_enabled": True,
        "object_detection_enabled": False,
        "object_detector_backend": "null",
        "scene_understanding_enabled": False,
        "gesture_recognition_enabled": False,
        "behavior_interpretation_enabled": False,
        "temporal_stabilization_enabled": True,
        "temporal_stabilization_activation_hits": 2,
        "temporal_stabilization_deactivation_hits": 2,
        "temporal_stabilization_hold_seconds": 1.25,
        "continuous_capture_enabled": True,
        "continuous_capture_target_fps": 10.0,
        "continuous_capture_error_backoff_seconds": 0.5,
        "continuous_capture_stop_timeout_seconds": 2.0,
    },
    "pan_tilt": {
        "enabled": False,
        "i2c_bus": 1,
        "i2c_address": 64,
        "pwm_frequency_hz": 50,
        "pan_channel": 0,
        "tilt_channel": 1,
        "pan_min_angle": 45,
        "pan_center_angle": 90,
        "pan_max_angle": 135,
        "tilt_min_angle": 65,
        "tilt_center_angle": 90,
        "tilt_max_angle": 115,
        "step_degrees": 18,
        "servo_min_pulse_us": 500,
        "servo_max_pulse_us": 2500,
        "move_delay_seconds": 0.12,
        "settle_seconds": 0.05,
    },
    "mobility": {
        "enabled": False,
        "base_type": "differential",
        "safety_stop_enabled": True,
        "max_linear_speed": 0.3,
        "max_turn_speed": 0.5,
    },
    "benchmarks": {
        "enabled": True,
        "persist_turns": True,
        "path": "var/data/turn_benchmarks.json",
        "max_samples": 300,
        "summary_window": 30,
    },
    "benchmark_validation": {
        "path": "var/data/turn_benchmarks.json",
        "window_size": 30,
        "min_completed_turns": 5,
        "min_voice_samples": 5,
        "min_skill_samples": 3,
        "min_llm_samples": 3,
        "max_avg_wake_latency_ms": 450.0,
        "max_avg_stt_latency_ms": 1800.0,
        "max_avg_skill_latency_ms": 350.0,
        "max_avg_response_first_audio_ms": 1200.0,
        "max_avg_route_to_first_audio_ms": 1600.0,
        "max_avg_llm_first_chunk_ms": 1200.0,
        "max_avg_llm_response_first_audio_ms": 1800.0,
        "max_p95_skill_turn_ms": 3500.0,
        "max_p95_llm_turn_ms": 20000.0,
        "max_p95_total_turn_ms": 7000.0,
        "max_error_rate": 0.15,
        "min_llm_streaming_ratio": 0.8,
    },
    "premium_validation": {
        "voice_skill_turn_target": 8,
        "llm_short_turn_target": 5,
        "llm_long_turn_target": 3,
        "barge_in_turn_target": 3,
        "reminder_turn_target": 2,
    },
}


__all__ = ["DEFAULT_SETTINGS"]