WAKE_GATE_TIMEOUT_SECONDS = 2.2
FOLLOW_UP_WINDOW_SECONDS = 12.0
INITIAL_COMMAND_WINDOW_SECONDS = 6.5
POST_RESPONSE_GRACE_WINDOW_SECONDS = 8.0
INPUT_READY_MAX_WAIT_SECONDS = 2.0
DUPLICATE_TRANSCRIPT_COOLDOWN_SECONDS = 1.4
ACTIVE_IGNORE_LOG_COOLDOWN_SECONDS = 5.0

# Dedicated wake capture owns the microphone in standby.
# STT wake fallback is intentionally disabled in this architecture.
WAKE_STT_FALLBACK_ENABLED = False
WAKE_STT_FALLBACK_AFTER_MISSES = 999999
WAKE_STT_FALLBACK_TIMEOUT_SECONDS = 1.2
WAKE_STT_FALLBACK_COOLDOWN_SECONDS = 6.0

WAKE_REARM_SETTLE_SECONDS = 0.45
COMMAND_EMPTY_RETRY_LIMIT = 1
GRACE_EMPTY_RETRY_LIMIT = 2
FOLLOW_UP_EMPTY_RETRY_LIMIT = 3
COMMAND_IGNORE_RETRY_LIMIT = 1
GRACE_IGNORE_RETRY_LIMIT = 1
FOLLOW_UP_IGNORE_RETRY_LIMIT = 3
MIN_INLINE_COMMAND_ALPHA_CHARS = 3
MAX_ISOLATED_WAKE_TOKENS = 3

PHASE_COMMAND = "command"
PHASE_FOLLOW_UP = "follow_up"
PHASE_GRACE = "grace"