from __future__ import annotations

ACTION_TO_TOOL: dict[str, str] = {
    "help": "system.help",
    "status": "system.status",
    "memory_list": "memory.list",
    "memory_clear": "memory.clear",
    "memory_store": "memory.store",
    "memory_recall": "memory.recall",
    "memory_forget": "memory.forget",
    "reminders_list": "reminders.list",
    "reminders_clear": "reminders.clear",
    "reminder_create": "reminders.create",
    "reminder_delete": "reminders.delete",
    "timer_start": "timer.start",
    "timer_stop": "timer.stop",
    "focus_start": "focus.start",
    "break_start": "break.start",
    "introduce_self": "assistant.introduce",
    "ask_time": "clock.time",
    "show_time": "clock.time",
    "ask_date": "clock.date",
    "show_date": "clock.date",
    "ask_day": "clock.day",
    "show_day": "clock.day",
    "ask_month": "clock.month",
    "show_month": "clock.month",
    "ask_year": "clock.year",
    "show_year": "clock.year",
    "exit": "system.sleep",
    "shutdown": "system.shutdown",
    "confirm_yes": "dialogue.confirm",
    "confirm_no": "dialogue.confirm",
}

DIRECT_ACTIONS = {
    "help",
    "status",
    "memory_list",
    "memory_clear",
    "memory_store",
    "memory_recall",
    "memory_forget",
    "reminders_list",
    "reminders_clear",
    "reminder_create",
    "reminder_delete",
    "timer_start",
    "timer_stop",
    "focus_start",
    "break_start",
    "introduce_self",
    "ask_time",
    "show_time",
    "ask_date",
    "show_date",
    "ask_day",
    "show_day",
    "ask_month",
    "show_month",
    "ask_year",
    "show_year",
    "exit",
    "shutdown",
}

ALWAYS_EXPLICIT_ACTIONS = {
    "status",
    "memory_list",
    "memory_clear",
    "memory_store",
    "memory_recall",
    "memory_forget",
    "reminders_list",
    "reminders_clear",
    "reminder_create",
    "reminder_delete",
    "timer_start",
    "timer_stop",
    "introduce_self",
    "ask_time",
    "show_time",
    "ask_date",
    "show_date",
    "ask_day",
    "show_day",
    "ask_month",
    "show_month",
    "ask_year",
    "show_year",
    "exit",
    "shutdown",
    "confirm_yes",
    "confirm_no",
}

EXPLICIT_FOCUS_PATTERNS = (
    r"\bstart focus\b",
    r"\bstart focus mode\b",
    r"\bfocus mode\b",
    r"\bfocus session\b",
    r"\bwlacz focus\b",
    r"\bwłącz focus\b",
    r"\bzacznij focus\b",
    r"\bsesja focus\b",
    r"\btryb skupienia\b",
    r"\bsesja nauki\b",
)

EXPLICIT_BREAK_PATTERNS = (
    r"\bstart break\b",
    r"\bstart break mode\b",
    r"\bbreak mode\b",
    r"\btake a break\b",
    r"\bwlacz przerwe\b",
    r"\bwłącz przerwę\b",
    r"\bzacznij przerwe\b",
    r"\bzacznij przerwę\b",
    r"\btryb przerwy\b",
    r"\bprzerwa\b",
)

EXPLICIT_HELP_PATTERNS = (
    r"^help$",
    r"^show help$",
    r"^open help$",
    r"^show menu$",
    r"^open menu$",
    r"^what can you do$",
    r"^how can you help me$",
    r"^pomoc$",
    r"^pokaz pomoc$",
    r"^pokaż pomoc$",
    r"^pokaz menu$",
    r"^pokaż menu$",
    r"^co potrafisz$",
    r"^co umiesz$",
    r"^jak mozesz mi pomoc$",
    r"^jak możesz mi pomóc$",
)

CONVERSATION_TOPIC_PATTERNS: dict[str, tuple[str, ...]] = {
    "low_energy": (
        r"\bi am tired\b",
        r"\bi feel tired\b",
        r"\bi m tired\b",
        r"\bi am exhausted\b",
        r"\bi feel exhausted\b",
        r"\bi am sleepy\b",
        r"\bi feel sleepy\b",
        r"\bi do not feel well\b",
        r"\bi dont feel well\b",
        r"\bjestem zmeczony\b",
        r"\bjestem zmeczona\b",
        r"\bczuje sie zmeczony\b",
        r"\bczuje sie zmeczona\b",
        r"\bczuje sie zle\b",
        r"\bnie czuje sie dobrze\b",
        r"\bzle sie czuje\b",
        r"\bchce mi sie spac\b",
        r"\bjestem senny\b",
        r"\bjestem senna\b",
    ),
    "focus_struggle": (
        r"\bi cannot focus\b",
        r"\bi cant focus\b",
        r"\bi can not focus\b",
        r"\bi cannot concentrate\b",
        r"\bi cant concentrate\b",
        r"\bi can not concentrate\b",
        r"\bi am distracted\b",
        r"\bi feel distracted\b",
        r"\bnie moge sie skupic\b",
        r"\bnie umiem sie skupic\b",
        r"\bnie moge sie skoncentrowac\b",
        r"\bnie moge sie dzisiaj skupic\b",
        r"\bciezko mi sie skupic\b",
        r"\bnie mam skupienia\b",
        r"\brozprasza mnie\b",
    ),
    "overwhelmed": (
        r"\bi feel overwhelmed\b",
        r"\bi am overwhelmed\b",
        r"\bi have too much to do\b",
        r"\btoo much to do\b",
        r"\bi feel stressed\b",
        r"\bi am stressed\b",
        r"\bmam za duzo do zrobienia\b",
        r"\bmam duzo do zrobienia\b",
        r"\bjestem przytloczony\b",
        r"\bjestem przytloczona\b",
        r"\bczuje sie przytloczony\b",
        r"\bczuje sie przytlocona\b",
        r"\bstresuje sie\b",
    ),
    "study_help": (
        r"\bi need help studying\b",
        r"\bhelp me study\b",
        r"\bi need help with studying\b",
        r"\bcan you help me study\b",
        r"\bmusze sie uczyc\b",
        r"\bpotrzebuje pomocy w nauce\b",
        r"\bpomoz mi sie uczyc\b",
        r"\bpomoz mi w nauce\b",
        r"\bmusze sie skupic na nauce\b",
    ),
    "encouragement": (
        r"\bcheer me up\b",
        r"\bmotivate me\b",
        r"\bi feel lazy\b",
        r"\bi am lazy\b",
        r"\bi need motivation\b",
        r"\bpodnies mnie na duchu\b",
        r"\bzmotywuj mnie\b",
        r"\bnie chce mi sie\b",
        r"\bjestem leniwy\b",
        r"\bjestem leniwa\b",
        r"\bpotrzebuje motywacji\b",
    ),
    "small_talk": (
        r"\bcan we talk\b",
        r"\bcan we talk for a minute\b",
        r"\btalk to me\b",
        r"\bcan you talk with me\b",
        r"\bcan you stay with me\b",
        r"\bi had a difficult day\b",
        r"\bi had a hard day\b",
        r"\bi feel bad\b",
        r"\bpogadaj ze mna\b",
        r"\bmozemy pogadac\b",
        r"\bmozemy porozmawiac chwile\b",
        r"\bporozmawiaj ze mna chwile\b",
        r"\bchce pogadac\b",
        r"\bmialem trudny dzien\b",
        r"\bmialam trudny dzien\b",
        r"\bslaby dzien\b",
    ),
    "humour": (
        r"\btell me a joke\b",
        r"\btell me something funny\b",
        r"\bsay something funny\b",
        r"\bpowiedz cos smiesznego\b",
        r"\bpowiedz cos zabawnego\b",
        r"\bpowiedz dowcip\b",
        r"\bopowiedz dowcip\b",
        r"\brozsmiesz mnie\b",
        r"\bzart\b",
    ),
    "riddle": (
        r"\btell me a riddle\b",
        r"\bgive me a riddle\b",
        r"\bask me a riddle\b",
        r"\bzadaj mi zagadke\b",
        r"\bpowiedz zagadke\b",
        r"\bopowiedz zagadke\b",
        r"\bdaj mi zagadke\b",
        r"\bzagadka\b",
    ),
    "interesting_fact": (
        r"\btell me something interesting\b",
        r"\btell me something interesting about animals\b",
        r"\btell me an animal fact\b",
        r"\bpowiedz mi cos ciekawego\b",
        r"\bopowiedz mi cos ciekawego\b",
        r"\bopowiedz mi cos ciekawego o zwierzetach\b",
        r"\bciekawostka\b",
    ),
}

TOPIC_PRIORITY = {
    "humour": 100,
    "riddle": 95,
    "interesting_fact": 90,
    "knowledge_query": 80,
    "small_talk": 70,
    "overwhelmed": 65,
    "focus_struggle": 64,
    "low_energy": 63,
    "study_help": 62,
    "encouragement": 61,
}

DIRECT_CONVERSATION_CUES = {
    "pl": {
        "pogadaj ze mna",
        "mozemy pogadac",
        "mozemy porozmawiac chwile",
        "porozmawiaj ze mna chwile",
        "chce pogadac",
        "powiedz cos smiesznego",
        "zadaj mi zagadke",
        "opowiedz mi cos ciekawego",
        "opowiedz mi cos ciekawego o zwierzetach",
        "zmotywuj mnie",
        "podnies mnie na duchu",
    },
    "en": {
        "can we talk",
        "can we talk for a minute",
        "talk to me",
        "can you talk with me for a minute",
        "tell me a joke",
        "tell me something funny",
        "say something funny",
        "tell me a riddle",
        "give me a riddle",
        "tell me something interesting",
        "tell me something interesting about animals",
        "cheer me up",
        "motivate me",
    },
}

QUESTION_STARTERS = {
    "pl": (
        "ile",
        "co",
        "czym",
        "kim",
        "kto",
        "gdzie",
        "kiedy",
        "dlaczego",
        "jak",
        "po co",
        "czy",
        "wytlumacz",
        "wyjasnij",
        "opowiedz",
    ),
    "en": (
        "what",
        "who",
        "where",
        "when",
        "why",
        "how",
        "how much",
        "how many",
        "can you explain",
        "explain",
        "tell me about",
    ),
}

GENERIC_KNOWLEDGE_PATTERNS = (
    r"\bhow much is\b",
    r"\bwhat is\b",
    r"\bwho is\b",
    r"\bwhere is\b",
    r"\bwhen is\b",
    r"\bwhy is\b",
    r"\bwhy does\b",
    r"\bhow does\b",
    r"\bhow do\b",
    r"\bexplain\b",
    r"\btell me about\b",
    r"\bile to jest\b",
    r"\bco to jest\b",
    r"\bczym jest\b",
    r"\bkim jest\b",
    r"\bgdzie jest\b",
    r"\bkiedy jest\b",
    r"\bdlaczego\b",
    r"\bjak dziala\b",
    r"\bwyjasnij\b",
    r"\bwytlumacz\b",
    r"\bopowiedz o\b",
)

MATH_PATTERNS = (
    r"^\s*\d+\s*[\+\-\*x/]\s*\d+\s*$",
    r"\b\d+\s*(plus|minus|times|multiplied by|divided by)\s*\d+\b",
    r"\b\d+\s*(dodac|dodać|minus|razy|podzielic przez|podzielić przez)\s*\d+\b",
    r"\bhow much is\b.*\d+",
    r"\bile to jest\b.*\d+",
)

__all__ = [
    "ACTION_TO_TOOL",
    "ALWAYS_EXPLICIT_ACTIONS",
    "CONVERSATION_TOPIC_PATTERNS",
    "DIRECT_ACTIONS",
    "DIRECT_CONVERSATION_CUES",
    "EXPLICIT_BREAK_PATTERNS",
    "EXPLICIT_FOCUS_PATTERNS",
    "EXPLICIT_HELP_PATTERNS",
    "GENERIC_KNOWLEDGE_PATTERNS",
    "MATH_PATTERNS",
    "QUESTION_STARTERS",
    "TOPIC_PRIORITY",
]